sudo: false
language: python
python:
- '3.6'
before_install:
- mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20150712/texlive.tar.xz
  | tar -JxC $HOME/texlive
- pip install Pygments
script:
- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
- pdflatex -shell-escape plato-fsm-memo
- bibtex plato-fsm-memo
- pdflatex -shell-escape plato-fsm-memo
- pdflatex -shell-escape plato-fsm-memo
deploy:
  provider: releases
  api_key:
    secure: CK6yx3ytyaf1RRbUevh032LoCbK2Gh4/QryBrHT2CZPU8dqqtM2vTwB9+K2UmXsQcH63XUVmo8isBrVaJXRMBJ5XdF20Zw9ZGTkQGr0UhSX8z9jMSxGHdf9i0JqP6rp51Np1w2TRNkkZXLGaN7Iinz4GeGUnuNaeWnYVOnq84d3vtK6NX0CDeO5yUCvbcpCJT90P50hPJMSLUHhgUAjhrf3OsRvyTLlPM+sMqmny9Z/5tr4w7tERTfrLin9VOMCoTXPIIdmJamTWXDZ+XQZ8MlmDm2Ye8Rk3IC6PAIrygept3b5nYLq+NPpEG9NfsM479FhQ1rchCunBZorrHWfHbscbbmTk5mxuvJHmAIPMcr9bAU4IIyM15Feh68wWUShcwt6ZwQvLs/8y7RFPPDzjmrLdoHn5dBqd2IoItKhvZr9geO2Le9faO3+35rKuvnvhCkmisKjVpnrjOeP8DyS8dvitz5NOFxKrfL4cBFfl7QNzWIIjjDqbFuKH7RHoVqElg7t/mLf3rGFUHNbjjCPW6iYrjEp66TOcZRyf6sH8NpHc8JsfLCF1Yqqsspcei2rz8I9QZWoVFhqU38FAGXeQSjQ6yTwr1lIvk99HVlA5tQI6BLUnsX2cIOcOPxSRKJeuYFtDSFPqaiwc/AUc4E49nDMq49o+Bs7TkIkCgb3CRUw=
  file: plato-fsm-memo.pdf
  on:
    repo: jrbeaumont/plato-fsm-techmemo
